# Parameter configuration
[edit_page]
  repo_url = "https://github.com/angelospk/dsn-ore"
  editable = false

[features]
  # Syntax highlighting
  syntax_highlighter = true
  math = false
  privacy_pack = false

[header]
  navbar_style = "light"
  navbar_font = "sans-serif"

[footer]
  copyright = { notice = "© {year} ΔΣ Νέων Ορεστιάδας", license = { enable = false } }

[icon]
  pack = "fas"
