baseURL = "https://angelospk.github.io/dsn-ore/" 
defaultContentLanguage = "el"
theme = "ananke"

[languages]
  [languages.el]
    languageName = "Ελληνικά"
    weight = 1
    title = "ΔΣ Νέων Ορεστιάδας"
    [languages.el.params]
      description = "Επίσημη ιστοσελίδα"

  [languages.en]
    languageName = "English"
    weight = 2
    title = "Youth Council of Orestiada"
    [languages.en.params]
      description = "Official website"

[params]
  favicon = ""
  site_logo = ""
  description = "Επίσημη ιστοσελίδα"
  featured_image = ""
  recent_posts_number = 3