# ΑΝΤΙΚΑΤΕΣΤΗΣΕ ΤΑ ΚΕΦΑΛΑΙΑ ΜΕ ΤΑ ΔΙΚΑ ΣΟΥ
baseURL = "https://angelospk.github.io/dsn-ore/" 
languageCode = "el"
title = "ΔΣ Νέων Ορεστιάδας"
theme = "ananke" # Θα χρησιμοποιήσουμε το Ananke για σταθερότητα τώρα

# ΑΥΤΟ ΛΥΝΕΙ ΤΟ ΠΡΟΒΛΗΜΑ ΜΕ ΤΑ LINK ΣΤΟΝ ΥΠΟΦΑΚΕΛΟ
canonifyURLs = true
relativeURLs = false

[params]
  description = "Επίσημη ιστοσελίδα"
  # Προσοχή: Στο Ananke η εικόνα λέγεται featured_image