backend:
  name: github
  repo: angelospk/dsn-ore
  branch: main
  base_url: ""

media_folder: "static/uploads"
public_folder: "/dsn-ore/uploads"

collections:
  - name: "posts"
    label: "Άρθρα"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Τίτλος", name: "title", widget: "string"}
      - {label: "Ημερομηνία", name: "date", widget: "datetime"}
      - {label: "Περίληψη", name: "summary", widget: "text"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Κείμενο", name: "body", widget: "markdown"}
      - label: "Εικόνα"
        name: "image"
        widget: "object"
        fields:
          - {label: "Αρχείο", name: "filename", widget: "image"}
          - {label: "Λεζάντα", name: "caption", widget: "string", required: false}
          - {label: "Alt Text", name: "alt_text", widget: "string", required: false}

  - name: "pages"
    label: "Σελίδες"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - {label: "Τίτλος", name: "title", widget: "string"}
          - {label: "Περίληψη", name: "summary", widget: "text"}
          - {label: "Κείμενο", name: "body", widget: "markdown"}
