backend:
  name: github
  repo: angelospk/dsn-ore
  branch: main
  base_url: ""

media_folder: "static/uploads"
public_folder: "/dsn-ore/uploads"

collections:
  - name: "posts"
    label: "Ανακοινώσεις"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Τίτλος", name: "title", widget: "string"}
      - {label: "Ημερομηνία", name: "date", widget: "datetime"}
      - {label: "Εικόνα", name: "image", widget: "image", required: false}
      - {label: "Περίληψη", name: "description", widget: "text"}
      - {label: "Κείμενο", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Σελίδες"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - {label: "Τίτλος", name: "title", widget: "string"}
          - {label: "Κείμενο", name: "body", widget: "markdown"}
