backend:
  name: github
  repo: angelospk/dsn-ore
  branch: main
  base_url: ""

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Άρθρα"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Τίτλος", name: "title", widget: "string"}
      - {label: "Ημερομηνία", name: "pubDate", widget: "datetime"}
      - {label: "Περίληψη", name: "description", widget: "text"}
      - {label: "Εικόνα", name: "heroImage", widget: "image", required: false}
      - {label: "Κείμενο", name: "body", widget: "markdown"}
